name: Add new issues to project

# **What it does**:
# **Why we have it**:
# **Who does it impact**:

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  triage_issues:
    if: github.repository == 'github/docs'
    runs-on: ubuntu-latest

    steps:
      - name: Triage to project board
        uses: konradpabjan/actions-add-new-issue-to-column@v1.1
        with:
          action-token: ${{ secrets.GITHUB_TOKEN }}
          project-url: 'https://github.com/RobotPiProject/RobotPiHEIG/projects/1'
          column-name: 'To do'